services:
  db:
    env_file:
      - .env
    image: postgres:15
    restart: always
    ports:
      - "32581:5432"
    volumes:
      - postgres:/var/lib/postgresql
    networks:
      - activity

  nginx:
    env_file:
      - .env
    build:
      context: .        # context はアプリのソースがあるディレクトリ
      dockerfile: .dockerfiles/nginx/.Dockerfile  # 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/nginx.conf.template:ro
      - ./cert-copy/server.crt:/etc/nginx/certs/server.crt:ro
      - ./cert-copy/server.key:/etc/nginx/certs/server.key:ro
    networks:
      - activity

  app:
    env_file:
      - .env
    build:
      context: .        # context はアプリのソースがあるディレクトリ
      dockerfile: .dockerfiles/app/.Dockerfile  # ← 明示的にパスを指定
    ports:
      - "3000:3000"
      - "8787:8787"
      - "9000:9000"    
    networks:
      - activity

volumes:
  postgres:

networks:
  activity: