services:
  db:
    env_file:
      - .env
    image: postgres:15
    restart: always
    ports:
      - "32581:5432"
    volumes:
      - postgres:/var/lib/postgresql

  nginx:
    build:
      context: ./.dockerfiles/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  app:
    build:
      context: ./.dockerfiles/app/Dockerfile
    ports:
      - "3000:3000"
      - "8787:8787"
      - "9000:9000"    

volumes:
  postgres:
